services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    build:
      context: .
      dockerfile: docker/dev/app/Dockerfile
    env_file:
      - .env
      - .env.local
    ports:
      - "9003:9003"
    volumes:
      - .:/var/www/html
      - ./docker/dev/app/php.ini:/usr/local/etc/php/conf.d/app.ini
      - ./var/log:/var/www/html/var/log
    environment:
      APP_ENV: dev
      APP_DEBUG: 1

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    env_file:
      - .env
      - .env.local
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./var/log:/var/www/html/var/log

  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    env_file:
      - .env
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - ./var/postgresql/data:/var/lib/postgresql/data
      - ./var/postgresql/logs:/var/log/postgresql
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-app_db}
