services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: dev
      args:
        APP_ENV: dev
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        USER_NAME: ${USER_NAME:-appuser}
    volumes:
      - .:/var/www/html
      - ./docker/app/php.dev.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    ports:
      - "9003:9003"

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: postgres:16-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_db
    restart: always
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/lib/postgresql/logs
      - ./docker/postgresql/postgresql.dev.conf:/etc/postgresql/postgresql.conf:ro
      - ./docker/postgresql/pg_hba.dev.conf:/etc/postgresql/pg_hba.conf:ro
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-app_db}
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d ${DB_NAME:-app_db}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  dozzle:
    image: amir20/dozzle:latest
    container_name: ${COMPOSE_PROJECT_NAME}_dozzle
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  db_data:
  db_logs:
