services:
  app:
    build:
      target: dev
      args:
        USER: ${USER}
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${USER_ID:-1000}
        USER_NAME: ${USER_NAME}
        USER_EMAIL: ${USER_EMAIL}
    restart: "no"
    env_file:
      - path: .env
      - path: .env.local
        required: false
    environment:
      RUN_MIGRATIONS: "false"
    ports:
      - "127.0.0.1:${HTTP_WEB_PORT:-8080}:80"
    volumes:
      - ./:/app
    extra_hosts:
      - host.docker.internal:host-gateway
    deploy:
      resources:
        limits:
          memory: 2g
