services:
  app-tickets:
    build:
      target: dev
      args:
        USER: ${USER}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        USER_NAME: ${USER_NAME}
        USER_EMAIL: ${USER_EMAIL}
    restart: "no"
    env_file:
      - path: .env
      - path: .env.local
        required: false
    environment:
      FRANKENPHP_WORKER_CONFIG: |
        watch ./src/**/*.php
        watch ./config/**/*.{php,yaml,yml}
        watch ./templates/**/*.twig
        watch ./.env*
    ports:
      - "127.0.0.1:${HTTP_WEB_PORT:-8080}:80"
    volumes:
      - ./:/web
      - ~/.ssh:/home/${USER}/.ssh:ro
    extra_hosts:
      - host.docker.internal:host-gateway
    deploy:
      resources:
        limits:
          memory: 2g
