services:
  app:
    image: farmapremium_app:latest
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  nginx:
    image: nginx:1.29.1-alpine
    depends_on:
      app:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
