services:
  app:
    build:
      context: .
      dockerfile: docker/dev/app/Dockerfile
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:1.29.1-alpine
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
