networks:
  default:
    name: ${EXTERNAL_NET}
    external: true

services:
  app:
    build:
      context: .
      dockerfile: etc/Dockerfile
      target: prod
    restart: unless-stopped
    env_file: .env
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    deploy:
      resources:
        limits:
          memory: 1g

volumes:
  caddy_data:
  caddy_config:
