services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: dev
      args:
        APP_ENV: dev
    volumes:
      - .:/var/www/html
      - ./docker/app/php.ini.dev:/usr/local/etc/php/conf.d/php.ini
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    ports:
      - "9003:9003"

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf.dev:/etc/nginx/conf.d/default.conf:ro
  
  db:
    image: postgres:16-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_db
    restart: always
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/lib/postgresql/logs
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-app_db}
    ports:
      - "5432:5432"

  dozzle:
    image: amir20/dozzle:latest
    container_name: ${COMPOSE_PROJECT_NAME}_dozzle
    ports:
      - "9999:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: Europe/Madrid
    restart: unless-stopped

volumes:
  db_data:
  db_logs: