services:
  app:
    image: farmapremium_app:latest
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:1.29.1-alpine
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
